name: Build and Deploy Release

on:
  push:
    branches:
      - main  # Triggers the workflow on commits to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore --runtime win-x64

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish --runtime win-x64

    - name: Archive build output
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./publish

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ./publish

    - name: Create and Push Tag
      id: create_tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}        

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish
        asset_name: myapp.zip
        asset_content_type: application/zip

